---
title: "0708-1"
author: "uni:xw2598"
date: "7/8/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Single continuous outcome

##Structure & Relationship

Outcome : Y
Exposure : A,B,C
Covariates : D,F,G,H

relationship:

$$
E(Y|A,B,C,D,F,G,H) \sim N(\mu,\sigma)$$
 
$$E(A|D,F,G,H) \sim N(\mu,\sigma) \\$$
$$E(B|D,F,G,H) \sim N(\mu,\sigma) \\$$
$$E(c|D,F,G,H) \sim N(\mu,\sigma) \\$$

$$E(D) \sim bin(0.7) \\$$
$$E(F) \sim N(30,5) \\$$
$$E(G) \sim N(120,5) \\$$
$$E(H) \sim Poi(20)
$$

##1.First: try with small sample
```{r}
n = 1000

#covariates
d = rbinom(n,1,0.7)
e = rnorm(n,30,5)
f = rnorm(n,120,5)
h = rpois(n,20)

#exposures

b = 2.5*d+0.027*e+0.018*f+0.035*h +rnorm(n,0,0.5)
c = 1.5*d+0.013*e+0.008*f+0.35*h+rnorm(n,0,0.5)
d = 3.5*d+0.07*e+0.002*f+0.05*h+rnorm(n,0,0.5)

#response

y = 0.26*b+0.35*c+0.87*d+1.3*d+0.072*e+0.008*f+0.35*h+rnorm(n,0,0.5)


hist(y)

hist(b)
hist(c)
hist(d)
```

##2.g-formula

$$
g^* = f(a) = f(as,mn,pb) = f(as|mn,pb)*f(mn|pb)*f(pb) $$

$$E[Y_g*] = \int_a \int_c E(Y|A,C) * f^*(a)*f(c) dcda$$


```{r}

ipw = function(x,df,form){
# the numerator
mod_num <- lm(x ~ 1, data = df)

num <- dnorm(x = x, # treatment 
             mean = fitted.values(mod_num), # fitted values
             sd = summary(mod_num)$sigma) # model sigma
# the demonimator
mod_den <- lm(formula = form, data = df)

den <- dnorm(x = x, # treatment variable
             mean = fitted.values(mod_den), # fitted values
             sd = summary(mod_den)$sigma)
ipw_s = num/den
return(ipw_s)
}

```

#explanation of inverse propensity score function
```{r}
mod_num <- lm(x ~ 1, data = df)

num <- dnorm(x = x, # treatment 
             mean = fitted.values(mod_num), # fitted values
             sd = summary(mod_num)$sigma) # model sigma
# the demonimator
mod_den <- lm(formula = form, data = df)

den <- dnorm(x = x, # treatment variable
             mean = fitted.values(mod_den), # fitted values
             sd = summary(mod_den)$sigma)
ipw_s = num/den
```



##3.marginal structual model

```{r}

```






